[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = espidf

board_build_f_cpu = 240000000L
board_build.psram = disable
monitor_speed  = 115200
monitor_filters = esp32_exception_decoder
upload_speed   = 921600

extra_scripts = pre:scripts/gen_version.py