[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = espidf

board_build_f_cpu = 240000000L
board_build.psram = disable
monitor_speed  = 115200
upload_port = COM42
monitor_filters = esp32_exception_decoder
upload_speed   = 921600
build_flags = -I include
extra_scripts = pre:scripts/gen_version.py

[env:esp32dev_debug]
extends     = env:esp32dev
build_type  = debug
build_flags =
    -I include
    -DCORE_DEBUG_LEVEL=4
