name: Build ESP-IDF firmware

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1

    - name: Build project
      run: |
        . $IDF_PATH/export.sh
        idf.py build

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build